package fpconv

import (
	"math"
	"math/rand/v2"
	"strconv"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDtoa(t *testing.T) {
	// Expected strings were generated by the fpconv_dtoa implementation bundled
	// with Redis. Keep bit patterns explicit so parsing a decimal literal cannot
	// choose a different adjacent float before the function is exercised.
	tests := map[string]struct {
		bits     uint64
		expected string
	}{
		"positive zero": {
			bits:     0x0000000000000000,
			expected: "0",
		},
		"negative zero": {
			bits:     0x8000000000000000,
			expected: "-0",
		},
		"positive infinity": {
			bits:     0x7ff0000000000000,
			expected: "inf",
		},
		"negative infinity": {
			bits:     0xfff0000000000000,
			expected: "-inf",
		},
		"positive NaN": {
			bits:     0x7ff8000000000000,
			expected: "nan",
		},
		"negative NaN": {
			bits:     0xfff8000000000000,
			expected: "-nan",
		},
		"one": {
			bits:     0x3ff0000000000000,
			expected: "1",
		},
		"negative one": {
			bits:     0xbff0000000000000,
			expected: "-1",
		},
		"fraction": {
			bits:     0x3fb999999999999a,
			expected: "0.1",
		},
		"ordinary decimal": {
			bits:     0x40091eb851eb851f,
			expected: "3.14",
		},
		"plain small decimal": {
			bits:     0x3eb0c6f7a0b5ed8d,
			expected: "0.000001",
		},
		"scientific small decimal": {
			bits:     0x3e8421f5f40d8376,
			expected: "1.5e-7",
		},
		"scientific large decimal": {
			bits:     0x44dfde9f10a8d361,
			expected: "6.02e+23",
		},
		"large exponent": {
			bits:     0x54b249ad2594c37d,
			expected: "1e+100",
		},
		"small exponent": {
			bits:     0x2b2bff2ee48e0530,
			expected: "1e-100",
		},
		"smallest subnormal": {
			bits:     0x0000000000000001,
			expected: "5e-324",
		},
		"smallest normal": {
			bits:     0x0010000000000000,
			expected: "2.2250738585072014e-308",
		},
		"largest finite": {
			bits:     0x7fefffffffffffff,
			expected: "1.7976931348623157e+308",
		},
		"reported ambiguous value": {
			bits:     0x42e37d0c25bb8ea4,
			expected: "171422365113461.13",
		},
		"cached power regression": {
			bits:     0x44db1a300f9b83fc,
			expected: "511947894164106040000000",
		},
		// Multiplying this value by 100 lands on an integer, but dividing that
		// integer back by 100 selects a different float. Printing it as
		// "7927816.56" would therefore not round-trip.
		"two decimal near miss": {
			bits:     0x415e3e0223d70a3e,
			expected: "7.9278165600000005e+6",
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			value := math.Float64frombits(tc.bits)
			require.Equal(t, tc.expected, Dtoa(value))
		})
	}
}

func TestDtoa_fixedTwoDecimals(t *testing.T) {
	tests := []struct {
		value    float64
		expected string
	}{
		// Below the window; grisu2 already prints these in fixed notation.
		{value: 0.01, expected: "0.01"},
		{value: 0.09, expected: "0.09"},
		{value: 0.99, expected: "0.99"},

		// Inside the window.
		{value: 1.01, expected: "1.01"},
		{value: 10.01, expected: "10.01"},
		{value: 9999.99, expected: "9999.99"},
		{value: 9999999.99, expected: "9999999.99"},

		// Trailing zeros are trimmed rather than padded out to two decimals.
		{value: 1.5, expected: "1.5"},
		{value: 2.5, expected: "2.5"},
		{value: 3, expected: "3"},
		{value: 1e6, expected: "1000000"},

		// Above the window. Integral values switch to scientific notation from
		// 1e8 on, which is what keeps the fast path below 1e7.
		{value: 1e7, expected: "10000000"},
		{value: math.Nextafter(1e7, 0), expected: "9.999999999999998e+6"},
		{value: 1e8, expected: "1e+8"},
	}

	for _, tc := range tests {
		t.Run(tc.expected, func(t *testing.T) {
			require.Equal(t, tc.expected, Dtoa(tc.value))
			require.Equal(t, "-"+tc.expected, Dtoa(-tc.value))
		})
	}
}

func TestDtoa_roundTrip(t *testing.T) {
	// Exercise every binary exponent with values near both fraction boundaries.
	fractions := [...]uint64{0, 1, fracMask / 2, fracMask}
	for exponent := range uint64(0x7ff) {
		for _, fraction := range fractions {
			bits := exponent<<52 | fraction
			assertFpconvRoundTrip(t, bits)
			assertFpconvRoundTrip(t, bits|signMask)
		}
	}

	// Cover additional mantissas with a deterministic xorshift sequence.
	state := uint64(0x6a09e667f3bcc909)
	for range 10_000 {
		state ^= state << 13
		state ^= state >> 7
		state ^= state << 17
		if state&expMask != expMask {
			assertFpconvRoundTrip(t, state)
		}
	}
}

func assertFpconvRoundTrip(t *testing.T, bits uint64) {
	encoded := Dtoa(math.Float64frombits(bits))
	decoded, err := strconv.ParseFloat(encoded, 64)
	require.NoError(t, err, "bits %016x encoded as %q", bits, encoded)
	require.Equal(t, bits, math.Float64bits(decoded), "encoded as %q", encoded)
}

// sink keeps the formatted string observable. Discarding it instead lets the
// compiler inline strconv.FormatFloat and stack allocate its result.
var sink string

func Benchmark_Fpconv(b *testing.B) {
	rng := rand.New(rand.NewPCG(0x6a09e667f3bcc909, 0xbb67ae8584caa73b))

	shapes := []struct {
		name string
		data []float64
	}{
		{name: "random"},
		{name: "two decimals"},
	}
	for i := range shapes {
		shapes[i].data = make([]float64, 1024)
	}
	for i := range shapes[0].data {
		shapes[0].data[i] = rng.Float64()
		shapes[1].data[i] = float64(rng.IntN(1_000_000)) / 100
	}

	for _, shape := range shapes {
		data := shape.data

		b.Run(shape.name, func(b *testing.B) {
			b.Run("std", func(b *testing.B) {
				for i := range b.N {
					sink = strconv.FormatFloat(data[i%len(data)], 'g', -1, 64)
				}
			})

			b.Run("fpconv", func(b *testing.B) {
				for i := range b.N {
					sink = Dtoa(data[i%len(data)])
				}
			})
		})
	}
}
