package fpconv

// This file is a Go port of Redis's deps/fpconv/fpconv_dtoa.c and
// deps/fpconv/fpconv_powers.h.
//
// Fast and accurate double to string conversion based on Florian Loitsch's
// Grisu-algorithm[1].
//
// [1] https://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf
//
// The original implementation is distributed under the Boost Software
// License, Version 1.0:
//
// Copyright (c) 2021, Redis Labs
// Copyright (c) 2013-2019, night-shift <as.smljk at gmail dot com>
// Copyright (c) 2009, Florian Loitsch <florian.loitsch at inria dot fr>
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

import (
	"math"
	"math/bits"
	"strconv"
)

const (
	fracMask  uint64 = 0x000fffffffffffff
	expMask   uint64 = 0x7ff0000000000000
	hiddenBit uint64 = 0x0010000000000000
	signMask  uint64 = 0x8000000000000000
	expBias          = 1023 + 52

	firstPower = -348
	stepShift  = 3
	stepPowers = 1 << stepShift
	expMax     = -32
	expMin     = -60
)

type Fp struct {
	frac uint64
	exp  int
}

var tens = [...]uint64{
	10000000000000000000,
	1000000000000000000,
	100000000000000000,
	10000000000000000,
	1000000000000000,
	100000000000000,
	10000000000000,
	1000000000000,
	100000000000,
	10000000000,
	1000000000,
	100000000,
	10000000,
	1000000,
	100000,
	10000,
	1000,
	100,
	10,
	1,
}

var powersTen = [...]Fp{
	{18054884314459144840, -1220}, {13451937075301367670, -1193},
	{10022474136428063862, -1166}, {14934650266808366570, -1140},
	{11127181549972568877, -1113}, {16580792590934885855, -1087},
	{12353653155963782858, -1060}, {18408377700990114895, -1034},
	{13715310171984221708, -1007}, {10218702384817765436, -980},
	{15227053142812498563, -954}, {11345038669416679861, -927},
	{16905424996341287883, -901}, {12595523146049147757, -874},
	{9384396036005875287, -847}, {13983839803942852151, -821},
	{10418772551374772303, -794}, {15525180923007089351, -768},
	{11567161174868858868, -741}, {17236413322193710309, -715},
	{12842128665889583758, -688}, {9568131466127621947, -661},
	{14257626930069360058, -635}, {10622759856335341974, -608},
	{15829145694278690180, -582}, {11793632577567316726, -555},
	{17573882009934360870, -529}, {13093562431584567480, -502},
	{9755464219737475723, -475}, {14536774485912137811, -449},
	{10830740992659433045, -422}, {16139061738043178685, -396},
	{12024538023802026127, -369}, {17917957937422433684, -343},
	{13349918974505688015, -316}, {9946464728195732843, -289},
	{14821387422376473014, -263}, {11042794154864902060, -236},
	{16455045573212060422, -210}, {12259964326927110867, -183},
	{18268770466636286478, -157}, {13611294676837538539, -130},
	{10141204801825835212, -103}, {15111572745182864684, -77},
	{11258999068426240000, -50}, {16777216000000000000, -24},
	{12500000000000000000, 3}, {9313225746154785156, 30},
	{13877787807814456755, 56}, {10339757656912845936, 83},
	{15407439555097886824, 109}, {11479437019748901445, 136},
	{17105694144590052135, 162}, {12744735289059618216, 189},
	{9495567745759798747, 216}, {14149498560666738074, 242},
	{10542197943230523224, 269}, {15709099088952724970, 295},
	{11704190886730495818, 322}, {17440603504673385349, 348},
	{12994262207056124023, 375}, {9681479787123295682, 402},
	{14426529090290212157, 428}, {10748601772107342003, 455},
	{16016664761464807395, 481}, {11933345169920330789, 508},
	{17782069995880619868, 534}, {13248674568444952270, 561},
	{9871031767461413346, 588}, {14708983551653345445, 614},
	{10959046745042015199, 641}, {16330252207878254650, 667},
	{12166986024289022870, 694}, {18130221999122236476, 720},
	{13508068024458167312, 747}, {10064294952495520794, 774},
	{14996968138956309548, 800}, {11173611982879273257, 827},
	{16649979327439178909, 853}, {12405201291620119593, 880},
	{9242595204427927429, 907}, {13772540099066387757, 933},
	{10261342003245940623, 960}, {15290591125556738113, 986},
	{11392378155556871081, 1013}, {16975966327722178521, 1039},
	{12648080533535911531, 1066},
}

// Dtoa returns the exact representation Redis's fpconv_dtoa selects.
func Dtoa(value float64) string {
	var dest [64]byte
	length := 0
	negative := math.Float64bits(value)&signMask != 0
	if negative {
		dest[length] = '-'
		length++
	}

	if specialLength := filterSpecial(value, dest[length:]); specialLength != 0 {
		return string(dest[:length+specialLength])
	}
	// Fast path: values on the two-decimal grid are common in practice, and
	// grisu2 already prints them in fixed notation, so emit that directly.
	// The upper bound is not arbitrary: from 1e8 on, grisu2 switches integral
	// values to scientific notation ("1e+8"), which this path cannot produce.
	magnitude := math.Abs(value)
	if magnitude >= 1 && magnitude < 1e7 {
		if fixedLength := emitFixedTwoDecimals(magnitude, dest[length:]); fixedLength != 0 {
			return string(dest[:length+fixedLength])
		}
	}

	var digits [18]byte
	k := 0
	digitCount := grisu2(value, digits[:], &k)
	length += emitDigits(digits[:digitCount], dest[length:], k, negative)

	return string(dest[:length])
}

func emitFixedTwoDecimals(value float64, dest []byte) int {
	// Reconstructing the value rules out nearby binary floats whose
	// multiplication by 100 merely rounds to an integer.
	scaledValue := value * 100
	scaled := uint64(scaledValue)
	if scaledValue != float64(scaled) || float64(scaled)/100 != value {
		return 0
	}

	whole, fraction := scaled/100, scaled%100
	length := len(strconv.AppendUint(dest[:0], whole, 10))
	if fraction == 0 {
		return length
	}

	dest[length] = '.'
	length++
	dest[length] = byte(fraction/10) + '0'
	length++
	if fraction%10 != 0 {
		dest[length] = byte(fraction%10) + '0'
		length++
	}

	return length
}

func build(value float64) Fp {
	raw := math.Float64bits(value)
	fp := Fp{
		frac: raw & fracMask,
		exp:  int((raw & expMask) >> 52),
	}

	if fp.exp != 0 {
		fp.frac += hiddenBit
		fp.exp -= expBias
	} else {
		fp.exp = -expBias + 1
	}

	return fp
}

func normalize(fp *Fp) {
	for fp.frac&hiddenBit == 0 {
		fp.frac <<= 1
		fp.exp--
	}

	const shift = 64 - 52 - 1
	fp.frac <<= shift
	fp.exp -= shift
}

func normalizedBoundaries(fp Fp) (Fp, Fp) {
	upper := Fp{
		frac: (fp.frac << 1) + 1,
		exp:  fp.exp - 1,
	}

	for upper.frac&(hiddenBit<<1) == 0 {
		upper.frac <<= 1
		upper.exp--
	}

	const upperShift = 64 - 52 - 2
	upper.frac <<= upperShift
	upper.exp -= upperShift

	lowerShift := 1
	if fp.frac == hiddenBit {
		lowerShift = 2
	}
	lower := Fp{
		frac: (fp.frac << lowerShift) - 1,
		exp:  fp.exp - lowerShift,
	}
	lower.frac <<= uint(lower.exp - upper.exp)
	lower.exp = upper.exp

	return lower, upper
}

func multiply(a, b Fp) Fp {
	hi, lo := bits.Mul64(a.frac, b.frac)

	return Fp{
		frac: hi + lo>>63,
		exp:  a.exp + b.exp + 64,
	}
}

func roundDigit(digits []byte, delta, remainder, kappa, fraction uint64) {
	for remainder < fraction && delta-remainder >= kappa &&
		(remainder+kappa < fraction || fraction-remainder > remainder+kappa-fraction) {
		digits[len(digits)-1]--
		remainder += kappa
	}
}

func generateDigits(fp, upper, lower Fp, digits []byte, k *int) int {
	wfraction := upper.frac - fp.frac
	delta := upper.frac - lower.frac
	one := Fp{
		frac: uint64(1) << uint(-upper.exp),
		exp:  upper.exp,
	}
	part1 := upper.frac >> uint(-one.exp)
	part2 := upper.frac & (one.frac - 1)

	index := 0
	kappa := 10
	divIndex := 10
	for kappa > 0 && part1 < tens[divIndex] {
		divIndex++
		kappa--
	}
	for ; kappa > 0; divIndex++ {
		divisor := tens[divIndex]
		digit := part1 / divisor
		digits[index] = byte(digit) + '0'
		index++

		part1 -= digit * divisor
		kappa--

		tmp := (part1 << uint(-one.exp)) + part2
		if tmp <= delta {
			*k += kappa
			roundDigit(digits[:index], delta, tmp, divisor<<uint(-one.exp), wfraction)
			return index
		}
	}

	unitIndex := 18
	for {
		part2 *= 10
		delta *= 10
		kappa--

		digit := part2 >> uint(-one.exp)
		if digit != 0 || index != 0 {
			digits[index] = byte(digit) + '0'
			index++
		}

		part2 &= one.frac - 1
		if part2 < delta {
			*k += kappa
			roundDigit(digits[:index], delta, part2, one.frac, wfraction*tens[unitIndex])
			return index
		}

		unitIndex--
	}
}

func grisu2(value float64, digits []byte, k *int) int {
	w := build(value)
	lower, upper := normalizedBoundaries(w)
	normalize(&w)

	cachedPower, cachedExponent := findCachedPower10(upper.exp)
	w = multiply(w, cachedPower)
	upper = multiply(upper, cachedPower)
	lower = multiply(lower, cachedPower)
	lower.frac++
	upper.frac--
	*k = -cachedExponent

	return generateDigits(w, upper, lower, digits, k)
}

func emitDigits(digits, dest []byte, k int, negative bool) int {
	digitCount := len(digits)
	exponent := absInt(k + digitCount - 1)

	if k >= 0 && exponent < digitCount+7 {
		copy(dest, digits)
		for i := range k {
			dest[digitCount+i] = '0'
		}
		return digitCount + k
	}

	if k < 0 && (k > -7 || exponent < 4) {
		offset := digitCount - absInt(k)
		if offset <= 0 {
			offset = -offset
			dest[0] = '0'
			dest[1] = '.'
			for i := 0; i < offset; i++ {
				dest[2+i] = '0'
			}
			copy(dest[offset+2:], digits)
			return digitCount + 2 + offset
		}

		copy(dest, digits[:offset])
		dest[offset] = '.'
		copy(dest[offset+1:], digits[offset:])
		return digitCount + 1
	}

	maxDigits := 18
	if negative {
		maxDigits--
	}
	if digitCount > maxDigits {
		digitCount = maxDigits
		digits = digits[:digitCount]
	}

	index := 0
	dest[index] = digits[0]
	index++
	if digitCount > 1 {
		dest[index] = '.'
		index++
		copy(dest[index:], digits[1:])
		index += digitCount - 1
	}

	dest[index] = 'e'
	index++
	if k+digitCount-1 < 0 {
		dest[index] = '-'
	} else {
		dest[index] = '+'
	}
	index++

	century := 0
	if exponent > 99 {
		century = exponent / 100
		dest[index] = byte(century) + '0'
		index++
		exponent -= century * 100
	}
	if exponent > 9 {
		decade := exponent / 10
		dest[index] = byte(decade) + '0'
		index++
		exponent -= decade * 10
	} else if century != 0 {
		dest[index] = '0'
		index++
	}

	dest[index] = byte(exponent%10) + '0'
	return index + 1
}

func filterSpecial(value float64, dest []byte) int {
	if value == 0 {
		dest[0] = '0'
		return 1
	}

	raw := math.Float64bits(value)
	if raw&expMask != expMask {
		return 0
	}
	if raw&fracMask != 0 {
		copy(dest, "nan")
	} else {
		copy(dest, "inf")
	}
	return 3
}

func findCachedPower10(exponent int) (Fp, int) {
	const oneLogTen = 0.30102999566398114
	approximation := int(float64(-(exponent + len(powersTen))) * oneLogTen)
	// The numerator stays positive (its range is [33, 664] across every binary
	// exponent), so the shift matches the division the C original performs.
	index := (approximation - firstPower) >> stepShift

	for {
		current := exponent + powersTen[index].exp + 64
		if current < expMin {
			index++
			continue
		}
		if current > expMax {
			index--
			continue
		}

		return powersTen[index], firstPower + index*stepPowers
	}
}

func absInt(x int) int {
	if x < 0 {
		return -x
	}
	return x
}
